# Name of the pack
namesdfdf: MySQL / MariaDB

# Description of the pack
description: |+
  Official New Relic pack for MySQL and MariaDB
  Use this pack together with the New Relic MySQL On Host Integration to get insight into the performance of your MySQL and MariaDB instances.

# Support level
levelsssss: New Relic

# Design
logo: logo.png
website: https://en.wikipedia.org/wiki/MySQL

# Authors of the quickstart
authors:
  - New Relic

# Instrumentation
instrumentation:
  - type: newrelic-infra-ohi
    name: mysql
