name: Validate Packs

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.yml'
  # TODO: we want the following trigger for forks, but we will need to validate potentially insecure content.
  # it might be worth having this in its own workflow, depending on what we need to do.
  #
  # pull_request_target:
  #   paths:
  #     - '**/*.yml'

jobs:
  validate-packs:
    name: Validate Packs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'space-delimited'
      
      - name: Install dependencies
        run: |
          yarn install

      - name: Validate files
        id: validate-files
        run: |
          yarn validate-packs ${{ steps.changed-files.outputs.added_modified }}
